### ISSUE TITLE
Unable to find Image and CSV files

### ISSUE THREAD

**Issue by ZekeStarr** [MicrosoftLearning/MB-220-Dynamics365forMarketing#1]
# Module: 01
#### Step: 00

Can't find the 10 image files and 2 csv files [referenced](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/blob/master/Instructions/Labs/LAB%5BMB-220%5D_Lab01_Marketing_Application_Configuration.md#what-youll-need). Don't see them in the AllFiles/LabFiles, nor on the LDC.

**Comment by RobertRybaric** [comment]
Hi @ZekeStarr they have forgotten to include those files when moving from LDC to GitHub. If you have the previous package from LDC, it is there. Otherwise hope they will upload the files.

**Comment by ZekeStarr** [comment]
Thanks @RobertRybaric. Looks like it's all on GitHub now!

https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/blob/master/Allfiles/Labs/MB-220T00-Resources.zip
