### ISSUE TITLE
Mod 5 - lab 5.1 instructions do not reflect the template layout

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-220-Dynamics365forMarketing#49]
# Module: 05
#### Step: 10 , 12, 13 etc

Description of issue
* there is no date column
* there is no headline
* there is no link text
* the sections are limited

Repro steps:

I just worked around it to create the email, it was ok that way and it worked. it may be beneficial to add an image of the expected email outcome for Students / Learners to then ask people to replicate it as best as they could.

**Comment by anjenni** [comment]
Hi there! We are pushing an update this Friday (9/1) that will fix this issue. I will close this Issue out on that day. Thanks again for logging this.
