### ISSUE TITLE
Module 6 - real time marketing email - purpose greyed out and unable to be created.

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-220-Dynamics365forMarketing#50]
# Module: 06
#### Step: 03

Description of issue
Preview, test and go live with the email throws up 2 errors, as shown in the image below:
* from email address uses a domain that isn't authenticated for this organisation
* the purpose field is mandatory

Repro steps:

![image](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/89986870/b8e7892d-a0b2-4835-91df-ab84dabf2fb4)

* Please advise which email to use in the "from" field.
* 
* Please note that "selecting a purpose" is greyed out -  we are unable to create or select a purpose. This is also stopping us from going live with the email and thus halting the remainder of this exercise. Please advise.

**Comment by anjenni** [comment]
Thanks so much for bringing this to our attention. I'll be retesting this week and hope to have this bug closed by end of week.

**Comment by anjenni** [comment]
Hi there! We are pushing an update this Friday (9/1) that will fix this issue. I will close this Issue out on that day. Thanks again for logging this.
