### ISSUE TITLE
mod 7 - add surveys to marketing messages and customer journey is now different

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-220-Dynamics365forMarketing#51]
# Module: 7
#### Step: 4.4 

Description of issue
* when you update the button in this step, the instructions say to link to Survey - but this is not an option on the menu (even though survey integration is enabled in the feature settings.
*
![image](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/89986870/47405894-7005-43dd-b5b8-dd22b63213b3)

#### Step: 5.7 
* when the email tile has been added, the instructions say to add an item to the email elements. but there is not item to select customer voice survey anymore.
* 
![image](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/89986870/1be0811b-2bf0-44c7-a6bb-568bade6fe44)

**Comment by anjenni** [comment]
Thanks so much for bringing this to our attention. I'll be retesting this week and hope to have this bug closed by end of week.

**Comment by anjenni** [comment]
Hi there! We are pushing an update this Friday (9/1) that will fix this issue. I will close this Issue out on that day. Thanks again for logging this.
