### ISSUE TITLE
Lab 4.1 Ex 1: Copilot/Query Assist does not process prompt

### ISSUE THREAD

**Issue by SkillableMG** [MicrosoftLearning/MB-220-Dynamics365forMarketing#53]
- Module 4: Manage segments and consent
- Practice Lab 4.1: Work with segments
- Exercise 1: Create a segment
- steps 5-7

The Copilot / Query Assist feature fails to create a query from the prompt "Contacts with account Humongous Insurance". Manual creation of the query as a workaround succeeded. See the screenshots below.

![Screenshot 2023-12-27 112013](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/134323425/fc40070b-2d0a-446d-85c6-0d2c707c8814)

![Screenshot 2023-12-27 112028](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/134323425/4fa1f1f4-9f17-48d1-aca9-5cef96f4ce6c)

Repro steps:

1. Perform the above-referenced Lab 4.1 steps

**Comment by ephiax20** [comment]
Replicated this. 

I got the same outcome; "The natural language input service is still
learning some terms and phrases. Update
your input or skip to manual building."
