### ISSUE TITLE
Set up Customer Voice

### ISSUE THREAD

**Issue by LewisGoDeploy** [MicrosoftLearning/MB-220-Dynamics365forMarketing#57]
#### Step: 1

Description of issue
URL provided in step 1 of task 2 no longer takes you to a page where you can follow the instructions below.
The URL takes you here: https://learn.microsoft.com/en-us/dynamics365/customer-voice/purchase
There is no option to "Get started" or run a customer voice license trial for the lab
The fact you can't set up customer voice causes issues later on in the lab

Repro steps:

**Task 2 - Set up Customer Voice**
1. In a new browser tab, navigate to https://aka.ms/TryCustomerVoice
2. Select Continue or if you're not already signed in, enter the email address provided by the Authorized Lab Host.
3. Select Get Started.
4. Finally, select Skip & go to Dynamics 365 Customer Voice.
5. If you receive an error, wait a moment for the trial provisioning to finish and Refresh the page.

**Comment by anjenni** [comment]
Closed in 3/22 update.

**Comment by SkillableBB** [comment]
Hi @anjenni , we're still seeing customer voice unavailable for the user [p1].

[p1]

![CustomerVoiceError-ba64b5a2-4e67-4c66-93f4-f8ae0a2f232c](https://github.com/MicrosoftLearning/MB-220-Dynamics365forMarketing/assets/94069201/5ce1779f-b1b2-4c9d-95e1-455b14240695)

**Comment by anjenni** [comment]
@SkillableBB Hi there -

Yes, Customer Voice is no longer available as a trial, so every instance of CV was removed from the labs on 3/22. Users shouldn't need it to complete the labs anymore. Are you still seeing places where it is needed?

**Comment by SkillableBB** [comment]
Hi @anjenni, apologies about the confusion -- this matter is resolved.

**Comment by anjenni** [comment]
@SkillableBB no problem at all, I appreciate you checking in! :)
