### ISSUE TITLE
Missing Customer Journey From Entity Field

### ISSUE THREAD

**Issue by StevenLODS** [MicrosoftLearning/MB-220-Dynamics365forMarketing#8]
# Module: 00
#### Step: 4

Description of issue:

During step 4 of exercise 2, you're tasked with adding a new condition to your scoring model. In the entity field, you're supposed to have Customer Journey as one of the options to proceed and it's not located when searching for it.

Any advice or help on this would be greatly appreciated as I'm not sure if this is just a transient issue.

![image](https://user-images.githubusercontent.com/78036494/123872635-5dfe2c80-d903-11eb-9e80-88a57a5c8577.png)

**Comment by StevenLODS** [comment]
Anyone have any advice on this?

**Comment by anjenni** [comment]
Addressed in most recent update - thank you for raising this issue!
